# Generated by Django 3.1.2 on 2020-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProd', models.IntegerField(max_length=6)),
                ('NombreProd', models.CharField(max_length=150)),
                ('MarcaProd', models.CharField(max_length=150)),
                ('PrecioProd', models.IntegerField(max_length=8)),
                ('StockProd', models.IntegerField(max_length=4)),
                ('DescripciónProd', models.TextField(max_length=5000)),
            ],
        ),
    ]
