# Generated by Django 3.1.2 on 2020-10-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='PrecioProd',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='StockProd',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProd',
        ),
    ]
