# Generated by Django 3.1.2 on 2020-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20201013_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='PrecioProd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='StockProd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='idProd',
            field=models.IntegerField(help_text='Id única del producto', null=True),
        ),
    ]
