# Generated by Django 3.1.2 on 2020-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20201013_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProd',
            field=models.IntegerField(default=1, help_text='Id única del producto', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
