# Generated by Django 3.1.2 on 2020-10-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201013_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imageProd',
            field=models.ImageField(blank=True, null=True, upload_to='imagesProd/'),
        ),
    ]
