# Generated by Django 3.1.2 on 2020-10-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_imageprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imageProd',
        ),
    ]
