# Generated by Django 3.1.2 on 2020-10-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_remove_producto_imageprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imageProd',
            field=models.ImageField(blank=True, null=True, upload_to='imagesProd/'),
        ),
    ]
