# Generated by Django 3.1.2 on 2020-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20201019_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='CategoriaEsp',
            field=models.CharField(default=1, help_text='Categorias especiales (Destacados,Ofertas,Populares).Dejar vacio sino posee ', max_length=150),
            preserve_default=False,
        ),
    ]
