# Generated by Django 3.1.2 on 2020-10-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20201019_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='CategoriaEsp',
        ),
    ]
