# Generated by Django 3.1.2 on 2020-10-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_auto_20201019_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='CategoriaEsp',
            field=models.CharField(help_text='Categorias especiales (Destacados,Ofertas,Populares).Sino posee dejar como "Ninguno"', max_length=150, null=True),
        ),
    ]
