# Generated by Django 3.1.2 on 2020-10-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0015_producto_categoriaesp'),
        ('producto', '0002_auto_20201013_1518'),
    ]

    operations = [
    ]
