# Generated by Django 3.1.2 on 2020-10-27 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0017_auto_20201026_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idCompra', models.UUIDField(default=uuid.uuid4, help_text='Id única de la compra realizada', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
                ('numTelefonico', models.IntegerField(null=True)),
                ('comuna', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('idProducto', models.CharField(max_length=150)),
                ('comentario', models.CharField(max_length=150)),
            ],
        ),
    ]
