# Generated by Django 3.1.2 on 2020-10-27 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0018_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='idCompra',
            field=models.UUIDField(default=uuid.uuid4, help_text='Id única de la compra', primary_key=True, serialize=False),
        ),
    ]
