# Generated by Django 3.1.2 on 2020-10-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0019_auto_20201027_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
    ]
